In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv('Dataset/UCI_Credit_Card.csv')

In [5]:
data.head()


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [6]:
data.shape

(30000, 25)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
ID                            30000 non-null int64
LIMIT_BAL                     30000 non-null float64
SEX                           30000 non-null int64
EDUCATION                     30000 non-null int64
MARRIAGE                      30000 non-null int64
AGE                           30000 non-null int64
PAY_0                         30000 non-null int64
PAY_2                         30000 non-null int64
PAY_3                         30000 non-null int64
PAY_4                         30000 non-null int64
PAY_5                         30000 non-null int64
PAY_6                         30000 non-null int64
BILL_AMT1                     30000 non-null float64
BILL_AMT2                     30000 non-null float64
BILL_AMT3                     30000 non-null float64
BILL_AMT4                     30000 non-null float64
BILL_AMT5                     30000 non-null float64
BILL_AMT6   

In [10]:
data.isnull().values.any()

False

In [11]:
data['SEX'].value_counts()

2    18112
1    11888
Name: SEX, dtype: int64

In [12]:
data.apply(lambda x: sum(x.isnull()),axis=0)

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [13]:
features=data.drop(['ID'],axis=1)

In [14]:
features.rename(columns={'default.payment.next.month':'DEFAULT'},inplace=True)

In [15]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 24 columns):
LIMIT_BAL    30000 non-null float64
SEX          30000 non-null int64
EDUCATION    30000 non-null int64
MARRIAGE     30000 non-null int64
AGE          30000 non-null int64
PAY_0        30000 non-null int64
PAY_2        30000 non-null int64
PAY_3        30000 non-null int64
PAY_4        30000 non-null int64
PAY_5        30000 non-null int64
PAY_6        30000 non-null int64
BILL_AMT1    30000 non-null float64
BILL_AMT2    30000 non-null float64
BILL_AMT3    30000 non-null float64
BILL_AMT4    30000 non-null float64
BILL_AMT5    30000 non-null float64
BILL_AMT6    30000 non-null float64
PAY_AMT1     30000 non-null float64
PAY_AMT2     30000 non-null float64
PAY_AMT3     30000 non-null float64
PAY_AMT4     30000 non-null float64
PAY_AMT5     30000 non-null float64
PAY_AMT6     30000 non-null float64
DEFAULT      30000 non-null int64
dtypes: float64(13), int64(11)
memory usage: 5.5 

In [16]:
label_data=features['DEFAULT']

In [17]:
##label_data=pd.get_dummies(label_data)

In [18]:
features.drop(['DEFAULT'],axis=1)

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0        20000.0    2          2         1   24      2      2     -1     -1   
1       120000.0    2          2         2   26     -1      2      0      0   
2        90000.0    2          2         2   34      0      0      0      0   
3        50000.0    2          2         1   37      0      0      0      0   
4        50000.0    1          2         1   57     -1      0     -1      0   
5        50000.0    1          1         2   37      0      0      0      0   
6       500000.0    1          1         2   29      0      0      0      0   
7       100000.0    2          2         2   23      0     -1     -1      0   
8       140000.0    2          3         1   28      0      0      2      0   
9        20000.0    1          3         2   35     -2     -2     -2     -2   
10      200000.0    2          3         2   34      0      0      2      0   
11      260000.0    2          1         2   51     -1     -1     -1     -1   
12      630000.0    2          2         2   41     -1      0     -1     -1   
13       70000.0    1          2         2   30      1      2      2      0   
14      250000.0    1          1         2   29      0      0      0      0   
15       50000.0    2          3         3   23      1      2      0      0   
16       20000.0    1          1         2   24      0      0      2      2   
17      320000.0    1          1         1   49      0      0      0     -1   
18      360000.0    2          1         1   49      1     -2     -2     -2   
19      180000.0    2          1         2   29      1     -2     -2     -2   
20      130000.0    2          3         2   39      0      0      0      0   
21      120000.0    2          2         1   39     -1     -1     -1     -1   
22       70000.0    2          2         2   26      2      0      0      2   
23      450000.0    2          1         1   40     -2     -2     -2     -2   
24       90000.0    1          1         2   23      0      0      0     -1   
25       50000.0    1          3         2   23      0      0      0      0   
26       60000.0    1          1         2   27      1     -2     -1     -1   
27       50000.0    2          3         2   30      0      0      0      0   
28       50000.0    2          3         1   47     -1     -1     -1     -1   
29       50000.0    1          1         2   26      0      0      0      0   
...          ...  ...        ...       ...  ...    ...    ...    ...    ...   
29970   360000.0    1          1         1   34     -1     -1     -1      0   
29971    80000.0    1          3         1   36      0      0      0      0   
29972   190000.0    1          1         1   37      0      0      0      0   
29973   230000.0    1          2         1   35      1     -2     -2     -2   
29974    50000.0    1          2         1   37      1      2      2      2   
29975   220000.0    1          2         1   41      0      0     -1     -1   
29976    40000.0    1          2         2   47      2      2      3      2   
29977   420000.0    1          1         2   34      0      0      0      0   
29978   310000.0    1          2         1   39      0      0      0      0   
29979   180000.0    1          1         1   32     -2     -2     -2     -2   
29980    50000.0    1          3         2   42      0      0      0      0   
29981    50000.0    1          2         1   44      1      2      2      2   
29982    90000.0    1          2         1   36      0      0      0      0   
29983    20000.0    1          2         1   44     -2     -2     -2     -2   
29984    30000.0    1          2         2   38     -1     -1     -2     -1   
29985   240000.0    1          1         2   30     -2     -2     -2     -2   
29986   360000.0    1          1         2   35     -1     -1     -2     -2   
29987   130000.0    1          1         2   34      0      0      0      0   
29988   250000.0    1          1         1   34      0   

In [19]:
from sklearn.model_selection import train_test_split # very handy way of selecting sets

In [20]:
# Train Test Split
# Training Data = 80% of Dataset
# Test Data = 20% of Dataset


x_train,x_test,y_train,y_test=train_test_split(features,label_data,test_size=0.2,random_state=1,stratify=label_data)

In [21]:
x_train.shape

(24000, 24)

In [22]:
y_train.shape

(24000,)

In [23]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(24000, 24)
(6000, 24)
(24000,)
(6000,)


In [24]:
#Logistic regression

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(x_train,y_train)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [26]:
yr=LR.predict(x_test)

In [27]:
yr

array([0, 0, 0, ..., 0, 0, 0])

In [28]:
yr_prob=LR.predict_proba(x_test)

In [29]:
yr_prob

array([[0.75805684, 0.24194316],
       [0.65363449, 0.34636551],
       [0.78289365, 0.21710635],
       ...,
       [0.82997439, 0.17002561],
       [0.75077425, 0.24922575],
       [0.99556647, 0.00443353]])

In [30]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, yr)

0.7785

In [31]:
#Random Forest

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
RF=RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0).fit(x_train,y_train)

In [34]:
RF

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [35]:
Rr=RF.predict(x_test)

In [36]:
Rr

array([0, 0, 0, ..., 0, 0, 0])

In [37]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, Rr)

0.8781666666666667

In [38]:
#SVM

In [39]:
from sklearn.svm import SVC

In [40]:
svc=SVC(gamma='auto').fit(x_train,y_train)

In [41]:
svc

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [42]:
sr=svc.predict(x_test)

In [43]:
sr

array([0, 0, 0, ..., 0, 0, 0])

In [44]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, sr)

0.7796666666666666

In [45]:
#Neural Network

In [46]:
label_data=pd.get_dummies(label_data)

In [49]:
x_train1,x_test1,y_train1,y_test1=train_test_split(features,label_data,test_size=0.2,random_state=1,stratify=label_data)

In [50]:
x_train1.shape

(24000, 24)

In [51]:
y_train1.shape

(24000, 2)

In [52]:
y_train.head()

10029    0
17540    1
20357    1
20217    0
17264    1
Name: DEFAULT, dtype: int64

In [54]:
m,n=x_train1.shape
print(m)
print(n)

24000
24


In [56]:
import tensorflow as tf

In [108]:
learning_rate = 0.01
training_epochs = 15

tf.reset_default_graph()

# By aving 2 features: hours slept & hours studied
X = tf.placeholder(tf.float32, [None, n], name="X")
Y = tf.placeholder(tf.float32, [None, 2], name="Y")

In [109]:
# Initialize our weigts & bias
W = tf.get_variable("W", [n, 2], initializer = tf.contrib.layers.xavier_initializer())
b = tf.get_variable("b", [2], initializer = tf.zeros_initializer())
print(W.shape)

(24, 2)


In [110]:
Z = tf.add(tf.matmul(X, W), b)
prediction = tf.nn.sigmoid(Z)

In [111]:
cost = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits = Z, labels = Y))

In [112]:
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [113]:
init = tf.global_variables_initializer()

cost_history = np.empty(shape=[1],dtype=float)

In [114]:
with tf.Session() as sess:
    sess.run(init)
    
    for epoch in range(training_epochs):
        _, c = sess.run([optimizer, cost], feed_dict={X: x_train1, Y: y_train1})
        print("Epoch:", '%04d' % (epoch+1), "cost=", "{:.9f}".format(c), \
               "W=", sess.run(W), "b=", sess.run(b))
        cost_history = np.append(cost_history, c)
        
        
    # Calculate the correct predictions
    correct_prediction = tf.to_float(tf.greater(prediction, 0.5))

    # Calculate accuracy on the test set
    accuracy = tf.reduce_mean(tf.to_float(tf.equal(Y, correct_prediction)))
    print ("Accuracy:", accuracy.eval({X:x_train1, Y:y_train1}))
    print ("test Accuracy:", accuracy.eval({X:x_test1, Y:y_test1}))

Epoch: 0001 cost= 30966.656250000 W= [[ 0.08903158  0.420673  ]
 [ 0.05391096  0.34374774]
 [-0.17926933 -0.23727226]
 [-0.1615858   0.42520583]
 [-0.30155578  0.22691433]
 [-0.08525252 -0.05901212]
 [ 0.05927492  0.18290327]
 [ 0.01990187  0.29746446]
 [-0.17874925  0.06938319]
 [-0.22042252 -0.43155414]
 [ 0.32402575  0.09164577]
 [ 0.02140961  0.27530938]
 [-0.36234108  0.3128795 ]
 [ 0.4698807  -0.3575861 ]
 [-0.43614462  0.11005055]
 [-0.03543463 -0.11060096]
 [ 0.3258266  -0.43532762]
 [-0.4662194  -0.1821119 ]
 [ 0.44152635 -0.14007147]
 [ 0.45876944 -0.2857942 ]
 [-0.36612615  0.11817043]
 [ 0.01883606  0.3220139 ]
 [-0.03570204 -0.03039403]
 [-0.15819848  0.35377714]] b= [ 0.00999961 -0.00999999]
Epoch: 0002 cost= 29053.951171875 W= [[ 0.08186226  0.41067368]
 [ 0.04772941  0.33374864]
 [-0.18402988 -0.24727122]
 [-0.16676128  0.41520688]
 [-0.3081247   0.21691528]
 [-0.09516079 -0.04901285]
 [ 0.04957914  0.1929028 ]
 [ 0.01285775  0.3074646 ]
 [-0.18842976  0.07938364]
 [-0.